services:

  open-pool-manager:
    image: registry.livepeer.tools/open-pool-manager:v0.0.6
    restart: unless-stopped
    volumes:
      - pool-data:/var/lib/open-pool/data/
      - pool-config:/etc/open-pool
    command: ['/usr/local/bin/open-pool-manager', '-config=/etc/open-pool/config.json']
    environment:
      # Global default if no plugin-specific override is found.
      - LOG_LEVEL=info
      - LOG_LEVEL_STORAGE=info
      - LOG_LEVEL_DATALOADER=info
      - LOG_LEVEL_PAYOUTLOOP=info
      - LOG_LEVEL_API=info
volumes:
  pool-data:
    external: true
  pool-config:
    external: true